### PR TITLE
Localizations

### PR DESCRIPTION
**Pull request by humdingerb**

### CODE REVIEW

**Comment by humdingerb** [comment]
A question on:
> reporting.referencedumpexport.description=A dump of the system's supported languages, pkg categories, user-rating \
  stabilities and countries. Any localized text is in the language of the currently authenticated user.

What's the "Countries" above? Is it maybe the language of the user's commentary?

**Review by andponlin — APPROVED** [review]
LGTM

**Comment by andponlin** [comment]
> A question on:
> 
> > reporting.referencedumpexport.description=A dump of the system's supported languages, pkg categories, user-rating 
> >   stabilities and countries. Any localized text is in the language of the currently authenticated user.
> 
> What's the "Countries" above? Is it maybe the language of the user's commentary?

The countries are stored in the database (see [here](https://depot.haiku-os.org/__docs/datamodel.html)) and are used to denote the geographical position of a repository mirror. See [here](https://depot.haiku-os.org/#!/repository/haikuports/source/haikuports_x86_64) for a UI element where this is used.

**Comment by humdingerb** [comment]
Hi Andrew Lindesay!

On Sun, 18 Feb 2024 11:20:21 -0800 Andrew Lindesay wrote:
> > What's the "Countries" above? Is it maybe the language of the user's commentary?
> 
> The countries are stored in the database (see [here](https://depot.haiku-os.org/__docs/datamodel.html)) 
> and are used to denote the geographical position of a repository mirror.

Oh, I see. Wasn't aware of that.
I did misunderstand then and had to burden you with a new fixing PR... :)

Regards,
Humdinger

--
Help translating 3rd party Haiku applications
Go to Polyglot at https://i18n.kacperkasper.pl

**Pull request merged**
